name: build-docs
on:
  push:
    branches:
      - main
      - docs-dev
    paths:
      - "docs/**"
      - "mkdocs.yml"
      # - "harbor_cli/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: pip install mkdocs mkdocs-material mkdocstrings[python]
      - run: mkdocs gh-deploy --force
